train:
  model:
    name: IDFlows
    nflows: 8
    nbits: 8
    nsplit: 3
    H: 64
    W: 48
    C: 3
    couple:
      name: AdditiveCouple
      split: 0.75
      nn:
        name: DenseBlock
        growth_channel: 512
        depth: 8
        layer:
          name: DenseLayer
          act: LeakyReLU
      round:
        name: Round
        nbits: 8
    extenddim:
      name: ExtendDim
      scale: 2
    prior:
      name: Prior
      round:
        name: Round
        nbits: 8
      nn:
        name: DenseBlock
        growth_channel: 512
        depth: 8
        layer:
          name: DenseLayer
          act: LeakyReLU
    distribution:
      name: DLogistic
    round:
      name: Round
      nbits: 8

  train_dataloader:
    name: CommonDataLoader
    path: "/home/yanming/files/flow_project/data/img_align_train"
    batch_size: 32
    resize:
      - 64
      - 48
    centercrop:
      - 215
      - 178
    nbits: 8
    train: True
  test_dataloader:
    name: CommonDataLoader
    path: "/home/yanming/files/flow_project/data/img_align_test"
    batch_size: 16
    resize:
      - 64
      - 48
    centercrop:
      - 215
      - 178
    nbits: 8
    train: False
  
  optimizer:
    name: Adamax
    lr: 0.001
  scheduler:
    name: WarmUpScheduler
    warmup: 10
    beta: 0.99
  max_step: 1000000
  step_per_epoch: 1000
  evaluate_interval: 10000
  save_interval: 25000
  save_path: "./logs/model_for_celeba_64.pth"
  writer_path: "./logs/log_for_celeba_64"

