train:
  trainer: ResidualTrainer
  flows:
    name: ConditionalFlows
    nflows: 8
    nbits: 8
    nsplit: 3
    H: 64
    W: 64
    C: 3
    couple:
      name: AdditiveCouple
      split: 0.75
      nn:
        name: DenseBlock
        growth_channel: 512
        depth: 12
        layer:
          name: DenseLayer
          act: ReLU
      round:
        name: Round
        nbits: 8
    extenddim:
      name: ExtendDim
      scale: 2
    prior:
      name: Prior
      round:
        name: Round
        nbits: 8
      nn:
        name: DenseBlock
        growth_channel: 512
        depth: 12
        layer:
          name: DenseLayer
          act: ReLU
    distribution:
      name: DLogistic
    round:
      name: Round
      nbits: 8
    conv_for_cond: True
    
  vqvae:
    name: VQVAE
    checkpoint: '/home/yanming/files/IDFLOW/logs/vqvae_for_imagenet64_copy.pth'
    channel: 3
    embed_num: 16384
    embed_dim: 512
    encoder:
      name: VQEncoder
      block_num: 8
      block:
        name: ResBlock
        batch_norm: False
    decoder:
      name: VQDecoder
      block_num: 8
      block:
        name: ResBlock
        batch_norm: False
    distribution:
      name: BinomialDistribution
    vectorquantizer:
      reinit_interval: 1000
      threshold: 0.1
    hidden_dims:
      - 128
      - 256
      - 384 # // 8
    batch_norm: False
  
  input_size:
    - 64
    - 64
  
  patch_batch_size: 0

  train_dataloader:
    name: CustomDataLoader
    dataset:
      name: ImageNet64Dataset
      path: "/home/yanming/files/ImageNet64"
      size: 
        - 3
        - 64
        - 64
      train: True
    batch_size: 16
    nbits: 8
    train: True
  test_dataloader:
    name: CustomDataLoader
    dataset:
      name: ImageNet64Dataset
      path: "/home/yanming/files/ImageNet64/"
      size:
        - 3
        - 64
        - 64
      train: False
    batch_size: 16
    nbits: 8
    train: False
  
  optimizer:
    name: Adamax
    lr: 0.001
  scheduler:
    name: WarmUpScheduler
    warmup: 10
    beta: 0.99
  max_step: 1000000
  step_per_epoch: 1000
  evaluate_interval: 5000
  save_interval: 20000
  save_path: "./logs/resflows_imagenet64.pth"
  writer_path: "./logs/log_for_resflows_imagenet64"