train:
  trainer: ResidualTrainer
  flows:
    name: ConditionalFlows
    nflows: 8
    nbits: 8
    nsplit: 3
    H: 216
    W: 184
    C: 3
    couple:
      name: AdditiveCouple
      split: 0.75
      nn:
        name: DenseBlock
        growth_channel: 384
        depth: 8
        layer:
          name: DenseLayer
          act: LeakyReLU
      round:
        name: Round
        nbits: 8
    extenddim:
      name: ExtendDim
      scale: 2
    prior:
      name: Prior
      round:
        name: Round
        nbits: 8
      nn:
        name: DenseBlock
        growth_channel: 512
        depth: 12
        layer:
          name: DenseLayer
          act: LeakyReLU
    distribution:
      name: DLogistic
    round:
      name: Round
      nbits: 8
    conv_for_cond: True
    
  vqvae:
    name: VQVAE
    checkpoint: '/home/yanming/files/IDFLOW/logs/vqvae_for_celeba_full_reinit.pth'
    channel: 3
    embed_num: 8192
    embed_dim: 512
    encoder:
      name: VQEncoder
      block_num: 8
      block:
        name: ResBlock
        batch_norm: False
    decoder:
      name: VQDecoder
      block_num: 8
      block:
        name: ResBlock
        batch_norm: False
    distribution:
      name: BinomialDistribution
    vectorquantizer:
      reinit_interval: 1000
      threshold: 0.1
    hidden_dims:
      - 128
      - 256
      - 512 # // 8
    batch_norm: False
  
  input_size:
    - 216
    - 184
  
  patch_batch_size: 0

  train_dataloader:
    name: CommonDataLoader
    path: "/home/yanming/files/flow_project/data/img_align_train"
    batch_size: 4
    resize:
      - 215
      - 178
    centercrop:
      - 215
      - 178
    pad:
      - 1
      - 6
    nbits: 8
    train: True
  test_dataloader:
    name: CommonDataLoader
    path: "/home/yanming/files/flow_project/data/img_align_test"
    batch_size: 4
    resize:
      - 215
      - 178
    centercrop:
      - 215
      - 178
    pad:
      - 1
      - 6
    nbits: 8
    train: False
  
  optimizer:
    name: Adamax
    lr: 0.001
  scheduler:
    name: WarmUpScheduler
    warmup: 10
    beta: 0.99
  max_step: 1000000
  step_per_epoch: 1000
  evaluate_interval: 5000
  save_interval: 20000
  save_path: "./logs/resflows_direct_cond_conv_001.pth"
  writer_path: "./logs/log_for_resflows_direct_conv_001"