train:
  trainer: VQVAETrainer
  model:
    name: VQVAE
    channel: 3
    embed_num: 8192
    embed_dim: 512
    encoder:
      name: VQEncoder
      block_num: 8
      block:
        name: ResBlock
        batch_norm: False
    decoder:
      name: VQDecoder
      block_num: 8
      block:
        name: ResBlock
        batch_norm: False
    distribution:
      name: BinomialDistribution
    hidden_dims:
      - 128
      - 256
      - 512 # // 8
    batch_norm: False
  
  train_dataloader:
    name: CommonDataLoader
    path: "/home/yanming/files/flow_project/data/img_align_train"
    batch_size: 32
    resize:
      - 215
      - 178
    centercrop:
      - 215
      - 178
    pad:
      - 1
      - 6
    nbits: 8
    train: True
  test_dataloader:
    name: CommonDataLoader
    path: "/home/yanming/files/flow_project/data/img_align_test"
    batch_size: 32
    resize:
      - 215
      - 178
    centercrop:
      - 215
      - 178
    pad:
      - 1
      - 6
    nbits: 8
    train: False
  
  optimizer:
    name: Adam
    lr: 0.0001
  scheduler:
    name: WarmUpScheduler
    warmup: 10
    beta: 0.99
  max_step: 1000000
  step_per_epoch: 1000
  evaluate_interval: 5000
  save_interval: 20000
  save_path: "./logs/vqvae_for_celeba_full.pth"
  writer_path: "./logs/log_for_vqvae_for_celeba_full"
  train_args:
    alpha: 1.0
    beta: 0.1
    gamma: 0.25

